# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "85e1a9dba888450e33b84fbb067bc3a5"
name = "Try-On StyleLab"
application_url = "https://vton-production-890a.up.railway.app"
embedded = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "products/update", "app/uninstalled" ]
  uri = "https://stylelab-vtonn.onrender.com/webhooks/gdpr"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_orders,read_products,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://vton-production-890a.up.railway.app/api/auth/callback"
]

[app_proxy]
url = "https://vton-production-890a.up.railway.app"
subpath = "tryon"
prefix = "apps"

[build]
automatically_update_urls_on_dev = true
