# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "85e1a9dba888450e33b84fbb067bc3a5"
name = "Try-On StyleLab"
application_url = "https://vton-production-890a.up.railway.app"
embedded = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "products/update", "app/uninstalled" ]
  uri = "https://vton-production-890a.up.railway.app/webhooks"

  [[webhooks.subscriptions]]
  topics = [ "app_subscriptions/update" ]
  uri = "https://vton-production-890a.up.railway.app/webhooks/app_subscriptions/update"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "https://vton-production-890a.up.railway.app/webhooks/gdpr"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
# Scopes utilis√©s:
# - read_products: Pour afficher la liste des produits dans l'app
# - write_script_tags: Pour installer automatiquement le widget sur le storefront
scopes = "read_products,write_script_tags"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://vton-production-890a.up.railway.app/auth/callback"
]

[app_proxy]
url = "https://vton-production-890a.up.railway.app"
subpath = "tryon"
prefix = "apps"

[subscriptions]

  [subscriptions.starter]
  plans = [
    { name = "Starter", amount = 29.0, currency_code = "USD", interval = "EVERY_30_DAYS" }
  ]

  [subscriptions.pro]
  plans = [
    { name = "Pro", amount = 99.0, currency_code = "USD", interval = "EVERY_30_DAYS" }
  ]

  [subscriptions.studio]
  plans = [
    { name = "Enterprise", amount = 399.0, currency_code = "USD", interval = "EVERY_30_DAYS" }
  ]

[build]
automatically_update_urls_on_dev = true
