# Theme App Extension Configuration
# Learn more: https://shopify.dev/docs/apps/app-extensions/configuration

api_version = "2025-01"
name = "Virtual Try-On Widget"

uid = "d18f905c-9250-1dc8-ff03-4642490b6bb339a3139b"

type = "theme_app_extension"

[build]
command = ""
watch = []

[[extension_points]]
target = "app_embed"
module = "./blocks/block.liquid"

